### ISSUE TITLE
launching error

### ISSUE THREAD

**Issue by JeremyLegron** [fxmarty/rikai-mpv#2]
Hello,

Thank you very much for your work!
Your extension seems appealing to me, so I tried to install it.
I think I managed to make python and node communicate. However when I start rikai with F5 the subtitle disappear after a few seconds and I get the following error:

```[front] Starting rikai-mpv...
[rikai-mpv] Starting rikai-mpv in python...
Launching node.js backend...
Connecting from Python...
Checking for leftover socket.
Removing leftover socket.
Creating server.
python <---> node.js socket connected.
Connection acknowledged.
node client connected.
Traceback (most recent call last):
  File "/home/jeremy/.config/mpv/scripts/rikai-mpv/subtitles_popup_graphics.py", line 66, in mpv_fullscreen_status
    return loads(stdoutdata)['data']
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jeremy/.config/mpv/scripts/rikai-mpv/subtitles_popup_graphics.py", line 92, in main
    if mpv_fullscreen_status():
  File "/home/jeremy/.config/mpv/scripts/rikai-mpv/subtitles_popup_graphics.py", line 68, in mpv_fullscreen_status
    return mpv_fullscreen_status()
  File "/home/jeremy/.config/mpv/scripts/rikai-mpv/subtitles_popup_graphics.py", line 68, in mpv_fullscreen_status
    return mpv_fullscreen_status()
  File "/home/jeremy/.config/mpv/scripts/rikai-mpv/subtitles_popup_graphics.py", line 68, in mpv_fullscreen_status
    return mpv_fullscreen_status()
  [Previous line repeated 985 more times]
  File "/home/jeremy/.config/mpv/scripts/rikai-mpv/subtitles_popup_graphics.py", line 63, in mpv_fullscreen_status
    stdoutdata = subprocess.getoutput('echo \'{ "command": ["get_property", "fullscreen"] }\' | socat - "'
  File "/usr/lib/python3.9/subprocess.py", line 647, in getoutput
    return getstatusoutput(cmd)[1]
  File "/usr/lib/python3.9/subprocess.py", line 628, in getstatusoutput
    data = check_output(cmd, shell=True, text=True, stderr=STDOUT)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1769, in _execute_child
    self._close_pipe_fds(p2cread, p2cwrite,
  File "/usr/lib/python3.9/subprocess.py", line 1214, in _close_pipe_fds
    with contextlib.ExitStack() as stack:
  File "/usr/lib/python3.9/contextlib.py", line 390, in __init__
    self._exit_callbacks = deque()
RecursionError: maximum recursion depth exceeded while calling a Python object```

I have no idea how to solve this, could you give me any clue?
Thank you for your help.

**Comment by fxmarty** [comment]
Hello, thank you for your bug report! I am sorry that it is not working out of the box, I have tested it only on a single setup so I was indeed expecting it to break at points (but hopefully it will get better).

Could you share some infos on the setup you are running on? E.g., distrib, window manager, mpv version. I would like to try to reproduce the issue if I can.

The error shown comes from a piece of code detecting whether mpv is in full-screen or not, as right now we want to show the subs only when mpv is in full screen. It comes from interSubs: https://github.com/oltodosel/interSubs/blob/master/interSubs.py#L1123 (vs here https://github.com/fxmarty/rikai-mpv/blob/main/subtitles_popup_graphics.py#L62 ).

I think what happens is that `loads(stdoutdata)['data']` always fail in your case, basically leading to an infinite recursion call to `mpv_fullscreen_status()` due to the Exception calls.

Normally `loads(stdoutdata)` would be a string that looks like, e.g. `{"data":false,"error":"success"}` or `{"data":true,"error":"success"}`, from which we can determine whether we are in full-screen mode or not.

Something else you could do to help me out: could you try to add some printing in the `mpv_fullscreen_status()` function, and send me again some log? Like this (you can replace the whole function):

```python
def mpv_fullscreen_status():
    stdoutdata = subprocess.getoutput('echo \'{ "command": ["get_property", "fullscreen"] }\' | socat - "'
                                      + mpv_socket + '"')
    
    print(stdoutdata)
    
    try:
        return loads(stdoutdata)['data']
    except Exception as e:
        print(e)
        return mpv_fullscreen_status()
```

Edit: Something I can see: can you check you have `socat` installed on your system? Sorry, I forgot to mention it but it should be required too.

**Comment by JeremyLegron** [comment]
Thank you for your reply!
I didn't have socat installed on my system. I installed it and now it works fine!
I'm not providing the other info you asked as there is no point now that the problem is solved.
Thank you for the help, I'm gonna enjoy this plugin.

Regards

**Comment by fxmarty** [comment]
Glad it works now :)
